version: "3.7"

x-app-volumes: &app-volumes
  - .:/app:cached
  - ~/.bash_history:/root/.bash_history
  - bundle_cache:/bundle_cache

services:
  app:
    build: .
    volumes: *app-volumes
    depends_on:
      - chrome

  chrome:
    image: justinribeiro/chrome-headless
    ports:
      - 9222:9222
    cap_add:
      - SYS_ADMIN

volumes:
  bundle_cache:
